apiVersion: v1
kind: Service
metadata:
  name: weaviate
  namespace: dify
spec:
  selector:
    app: weaviate
  type: NodePort
  ports:
  - name: endpoint
    protocol: TCP
    port: 8080
    targetPort: 8080
  - name: grpc-endpoint
    protocol: TCP
    port: 50051
    targetPort: 50051