apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: dify
spec:
  selector:
    matchLabels:
      app: postgres
  serviceName: "postgres"
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: postgres
          image: postgres:15-alpine
          imagePullPolicy: IfNotPresent
          envFrom:
          - configMapRef:
              name: dify-config
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: dify-config
                  key: DB_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: dify-config
                  key: DB_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: dify-config
                  key: DB_DATABASE
            - name: PGDATA
              valueFrom:
                configMapKeyRef:
                  name: dify-config
                  key: PGDATA
          args:
          - postgres
          - -c
          - max_connections=$(POSTGRES_MAX_CONNECTIONS)
          - -c
          - shared_buffers=$(POSTGRES_SHARED_BUFFERS)
          - -c
          - work_mem=$(POSTGRES_WORK_MEM)
          - -c
          - maintenance_work_mem=$(POSTGRES_MAINTENANCE_WORK_MEM)
          - -c
          - effective_cache_size=$(POSTGRES_EFFECTIVE_CACHE_SIZE)
          - -c
          - statement_timeout=$(POSTGRES_STATEMENT_TIMEOUT)
          - -c
          - idle_in_transaction_session_timeout=$(POSTGRES_IDLE_IN_TRANSACTION_SESSION_TIMEOUT)
          ports:
            - containerPort: 5432
              name: postgres-port
          resources:
            limits:
              cpu: 100m
              memory: 300Mi
            requests:
              cpu: 100m
              memory: 100Mi
          livenessProbe:
            exec:
              command:
                - sh
                - '-c'
                - pg_isready -h 127.0.0.1 -U "$DB_USERNAME" -d "$DB_DATABASE"
            initialDelaySeconds: 5
            timeoutSeconds: 2
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 10
          readinessProbe:
            exec:
              command:
                - sh
                - '-c'
                - pg_isready -h 127.0.0.1 -U "$PGUSER" -d "$DB_DATABASE"
            initialDelaySeconds: 5
            timeoutSeconds: 2
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 10
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: db-data
              subPath: dify/volumes/db/data
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: dify-pvc